/**
 * entrevistaService — the RH/gestor interview workspace data layer (ENTREV-01..05).
 *
 * Clones the Phase-13 `revisaoRedacaoService` posture verbatim. The genuinely
 * load-bearing invariants (RNF-07a + LGPD):
 *  - Every read names its columns explicitly via `ENTREVISTA_ALLOWLIST` /
 *    `*_ALLOWLIST` consts — NEVER a star projection ([[reference_select_star_leaks_pii]]).
 *    RLS is row-level only and does NOT hide columns; the candidate's interview
 *    transcript + gestor notes + scores are PII, so over-projecting would leak
 *    more than the workspace needs. The candidate has NO read policy on these
 *    rows (denied at the DB); RH/admin are allowed (14-04 candidate-DENY RLS).
 *  - The scorecard WRITE goes through the LIVE `salvar_avaliacao_entrevista`
 *    SECURITY DEFINER RPC (role + own-vaga guarded). It NEVER writes
 *    `candidaturas`, NEVER advances the funil, NEVER auto-rejects.
 *  - The two AI surfaces (`gerar-guia-entrevista`, `avaliar-transcricao-entrevista`)
 *    are invoked via `supabase.functions.invoke`; the client body carries ONLY
 *    identifiers + raw text — never a score/band (anti-tamper; the 14-01 contract
 *    test parses these exact bodies under the EF `.strict()` schemas).
 *  - `confirmarRevisaoHumana` sets `entrevista_analises.revisao_confirmada_em`,
 *    which is the human-confirmed marker the server `avancar_etapa` guard reads to
 *    release the language/accent flag block.
 *
 * @module features/entrevista/services/entrevistaService
 * @see src/features/triagem/services/revisaoRedacaoService.ts (the exact analog)
 * @see supabase/migrations (salvar_avaliacao_entrevista RPC + avancar_etapa flag guard, 14-03/14-04)
 */
import { supabase } from '@/lib/supabase/client'
import type { StatusAgendamento } from '@/features/agendamento/services/agendamentoService'
import { extractEfErrorCode } from '@/lib/efErrors'
import type { Json } from '@/../database.types'

/** Service error mirroring the `camelCaseService.ts` convention (CLAUDE.md). */
export class EntrevistaServiceError extends Error {
  constructor(
    message: string,
    public code:
      | 'INVALID_INPUT'
      | 'NETWORK_ERROR'
      | 'DATABASE_ERROR'
      | 'FORBIDDEN'
      | 'NOT_FOUND',
    public details?: unknown,
  ) {
    super(message)
    this.name = 'EntrevistaServiceError'
  }
}

/** The two guide-generation modes (the EF `tipo` body field). */
export type TipoEntrevista = 'online' | 'presencial'

/** The 5 RH-only qualitative cognitive faixas (descriptive, never a verdict). */
export type BandaCognitiva =
  | 'bem_abaixo'
  | 'abaixo'
  | 'na_media'
  | 'acima'
  | 'bem_acima'

// ── Allowlist projections (NEVER a star projection — PII guard) ────────────────────

/**
 * The EXPLICIT column allowlist for the interview-guide read. NEVER `'*'`
 * ([[reference_select_star_leaks_pii]]). Listed as a single auditable constant.
 */
export const ENTREVISTA_GUIA_ALLOWLIST =
  'id, candidatura_id, tipo, guia, prompt_version, created_at, updated_at'

/**
 * The EXPLICIT column allowlist for the transcript-analysis read. Carries the
 * BARS competencies + citations + flags + the human-review markers
 * (revisao_confirmada_em is what unblocks the server avancar_etapa guard).
 */
export const ENTREVISTA_ANALISE_ALLOWLIST =
  'id, candidatura_id, status_analise, competencias, citacoes, bias_flags, bloqueio_avanco, scores_humanos, notas_humanas, revisada_por, revisao_confirmada_em, prompt_version, created_at'

/**
 * The EXPLICIT column allowlist for the scores read (the inline scorecard + the
 * RH-only cognitive band). NEVER `'*'`. Mirrors the live `scoresRhService`
 * projection — the candidate never reads `scores_candidato` (no RLS policy).
 */
export const ENTREVISTA_SCORES_ALLOWLIST =
  'id, candidatura_id, tipo, subtipo, score, score_max, status, metadata, citacoes, red_flags'

/**
 * The single auditable allowlist name the Wave-0 14-01 test source-probes
 * (`ENTREVISTA_ALLOWLIST = ...`). Aliases the guide projection so the contract
 * (an explicit, named allowlist exists; no star) is satisfied in one place.
 */
export const ENTREVISTA_ALLOWLIST = ENTREVISTA_GUIA_ALLOWLIST

/** Defensive bound on any RH read (no unbounded queries — WR-05 precedent). */
const READ_LIMIT = 100

// ── Row shapes (allowlist-projected) ─────────────────────────────────────────

/** One STAR/PEI guide question (the EF `guia.perguntas[]` shape). */
export interface GuiaPergunta {
  pergunta: string
  dimensao?: string | null
  /** The weak-dim score that motivated this question (online <3 / presencial <4). */
  score_atual?: number | null
  ancoras_bars?: Record<string, string> | string[] | null
  /**
   * Provenance of the question (ENTREV-08 audit). `'ia'` = AI-generated by the
   * `gerar-guia-entrevista` EF; `'manual'` = added/edited by the RH in the edit-mode
   * panel (20-04). The read layer (normalizeGuia) defaults legacy/missing → `'ia'`
   * (legacy guides are wholly AI-generated — no data backfill, A2).
   */
  origem?: 'ia' | 'manual'
  [k: string]: unknown
}

/** The interview-guide row, allowlist-projected. */
export interface EntrevistaGuiaRow {
  id: string
  candidatura_id: string
  tipo: string
  guia: { perguntas?: GuiaPergunta[]; foco?: string | null; [k: string]: unknown } | null
  prompt_version: string | null
  created_at: string
  /** Bumped by the save_entrevista_guia_edits upsert (20-02 migration). */
  updated_at?: string | null
}

/** One BARS competency dimension from the transcript analysis (AI-derived). */
export interface AnaliseCompetencia {
  competencia: string
  /**
   * The raw English key the EF persists (`competency`) — kept on the shape so the
   * normalization in `getAnalise` is non-lossy. Consumers read `competencia`.
   */
  competency?: string | null
  score?: number | null
  reasoning?: string | null
  bias_flags?: {
    content_dependent_only?: boolean
    regional_markers_ignored?: boolean
    disfluencies_ignored?: boolean
  } | null
  [k: string]: unknown
}

/** The transcript-analysis row, allowlist-projected. */
export interface EntrevistaAnaliseRow {
  id: string
  candidatura_id: string
  status_analise: string
  competencias: AnaliseCompetencia[] | null
  citacoes: unknown[] | null
  bias_flags: Record<string, unknown> | null
  /** SEGURA o avanço (RF-24) — true when the language/accent flag fired. */
  bloqueio_avanco: boolean
  scores_humanos: Record<string, unknown> | null
  notas_humanas: string | null
  revisada_por: string | null
  /** The human-confirmed marker the server avancar_etapa guard reads to unblock. */
  revisao_confirmada_em: string | null
  prompt_version: string | null
  created_at: string
}

/** One score row (the inline scorecard + the cognitive band), allowlist-projected. */
export interface EntrevistaScoreRow {
  id: string
  candidatura_id: string
  tipo: string
  subtipo: string | null
  score: number | null
  score_max: number | null
  status: string
  metadata: Record<string, unknown> | null
  citacoes: unknown[] | null
  red_flags: unknown[] | null
}

/** The candidate-context dashboard row (etapa + scheduled datetime), allowlisted. */
export interface EntrevistaContextoRow {
  candidatura_id: string
  vaga_id: string
  etapa_atual: string
  candidato_nome: string | null
  /** Horário da entrevista: agendamento ativo da candidatura (agendamentos_entrevista); fallback ao campo V1 da vaga. */
  entrevista_agendada_em: string | null
  /** Opt-in cognitive gate (default false). */
  aplica_cognitivo: boolean
}

// ── Reads (allowlist projections) ────────────────────────────────────────────

/**
 * Os status em que um agendamento ainda VALE — o que o painel deve exibir como horário.
 *
 * ⚠ 2026-09-06, no mesmo dia: o conserto da manhã filtrava `.eq('status', 'agendada')`.
 *   Bastou REAGENDAR (status → 'reagendada', o único caminho que a UI oferece para mudar
 *   a data) para o painel voltar a dizer «Sem horário definido» com a entrevista marcada
 *   para dali a 4 dias — a MESMA mensagem do defeito que aquele conserto resolvia. Uma
 *   lista literal de um item é uma fotografia do caminho feliz.
 *
 *   O critério é o complemento: valem os status que NÃO encerraram o agendamento.
 *   `cancelada` e `nao_compareceu` encerram; `em_andamento` e `concluida` não apagam a
 *   data (a entrevista aconteceu naquele horário). Espelha o `WHEN` do trigger
 *   `trg_notif_convite_reagendamento` (migration 20260906000004), que usa o mesmo conjunto
 *   ativo para decidir se reenvia o convite. O `satisfies` abaixo faz o compilador reprovar
 *   um valor novo do enum que não seja classificado aqui.
 */
const AGENDAMENTO_ENCERRADO = ['cancelada', 'nao_compareceu'] as const

export const AGENDAMENTO_ATIVO = [
  'agendada',
  'reagendada',
  'em_andamento',
  'concluida',
] as const satisfies readonly Exclude<
  StatusAgendamento,
  (typeof AGENDAMENTO_ENCERRADO)[number]
>[]

/**
 * Resolves the candidate context for the dashboard: the candidatura's vaga,
 * current etapa, candidate name, the manually-scheduled interview datetime, and
 * the cognitive opt-in. Allowlist projection — never a star projection. The `:id`
 * route param is a candidatura id.
 */
export async function getEntrevistaContexto(
  candidaturaId: string,
): Promise<EntrevistaContextoRow | null> {
  if (!candidaturaId) {
    throw new EntrevistaServiceError('candidaturaId é obrigatório', 'INVALID_INPUT')
  }
  const { data, error } = await supabase
    .from('candidaturas')
    .select(
      'id, vaga_id, etapa_atual, candidatos ( nome_completo ), vagas ( entrevista_agendada_em, aplica_cognitivo )',
    )
    .eq('id', candidaturaId)
    .maybeSingle()

  if (error) {
    throw new EntrevistaServiceError(
      `Não foi possível carregar o contexto da entrevista: ${error.message}`,
      'DATABASE_ERROR',
      error,
    )
  }
  if (!data) return null

  const raw = data as unknown as {
    id: string
    vaga_id: string
    etapa_atual: string
    candidatos?: { nome_completo?: string } | null
    vagas?: { entrevista_agendada_em?: string | null; aplica_cognitivo?: boolean } | null
  }
  // 2026-09-06: o horário vinha SÓ de `vagas.entrevista_agendada_em` — um campo por
  // VAGA (V1) que nada no app escreve. O painel dizia «Sem horário definido» com um
  // agendamento de 10/09 gravado em `agendamentos_entrevista` (Phase 35, por
  // candidatura). A fonte de verdade é o agendamento ativo mais recente da
  // candidatura; o campo da vaga fica só como fallback histórico.
  let agendadaEm: string | null = raw.vagas?.entrevista_agendada_em ?? null
  const { data: agendamento } = await supabase
    .from('agendamentos_entrevista')
    .select('data_hora')
    .eq('candidatura_id', candidaturaId)
    .in('status', AGENDAMENTO_ATIVO)
    .is('deleted_at', null)
    .order('data_hora', { ascending: false })
    .limit(1)
    .maybeSingle()
  const dataHora = (agendamento as { data_hora?: string | null } | null)?.data_hora
  if (typeof dataHora === 'string' && dataHora) agendadaEm = dataHora

  return {
    candidatura_id: raw.id,
    vaga_id: raw.vaga_id,
    etapa_atual: raw.etapa_atual,
    candidato_nome: raw.candidatos?.nome_completo ?? null,
    entrevista_agendada_em: agendadaEm,
    aplica_cognitivo: raw.vagas?.aplica_cognitivo ?? false,
  }
}

/**
 * Resolves the vaga id for a candidatura (the `:id` route param is a candidatura
 * id; some reads/writes are keyed by vaga). Allowlist projection — never
 * a star projection. Returns null when missing.
 */
export async function getVagaIdForCandidatura(candidaturaId: string): Promise<string | null> {
  if (!candidaturaId) {
    throw new EntrevistaServiceError('candidaturaId é obrigatório', 'INVALID_INPUT')
  }
  const { data, error } = await supabase
    .from('candidaturas')
    .select('vaga_id')
    .eq('id', candidaturaId)
    .maybeSingle()

  if (error) {
    throw new EntrevistaServiceError(
      `Não foi possível resolver a vaga: ${error.message}`,
      'DATABASE_ERROR',
      error,
    )
  }
  return (data as { vaga_id: string | null } | null)?.vaga_id ?? null
}

/**
 * One STAR/PEI guide question as it can appear inside the persisted `questions[]`
 * array. The EF emits English keys (`question`/`competency`); but a PRESERVED manual
 * row carries the pt-BR keys (`pergunta`/`dimensao`) — it was written by the RPC
 * (`saveGuiaEdits` → `{ perguntas: [{ pergunta, dimensao, origem:'manual' }] }`) and
 * then concatenated verbatim into the English-keyed `questions[]` by the EF merge
 * (`mergedQuestions = [...manualQs, ...freshIaQs]`). normalizeGuia therefore tolerates
 * BOTH key shapes per element so a manual row never normalizes to an empty `pergunta`
 * (CR-01) and never loses its `dimensao` (WR-02).
 */
interface EfGuiaQuestion {
  question?: string
  competency?: string
  /** pt-BR shape — present on a preserved manual row living under `questions[]` (CR-01/WR-02). */
  pergunta?: string
  dimensao?: string | null
  bars_anchors?: unknown
  /** Provenance, when present (the EF stamps `'ia'`; RH edits stamp `'manual'`). */
  origem?: string
  [k: string]: unknown
}

/**
 * Bridges the EF-persisted interview guide to the shape the RH panel reads
 * (ENTREV-GUIA-DISPLAY-01 — [[feedback_integration_contract_gap]]).
 *
 * `gerar-guia-entrevista` persists `guia` under its `InterviewGuideSchema` OUTPUT shape:
 * `{ questions: [{ question, competency, bars_anchors, ... }], ... }` (English keys). The
 * RH panel (`GuiaEntrevistaPanel.perguntasOf` + `PerguntaRow`) reads `guia.perguntas[]`
 * with `pergunta`/`dimensao` (pt-BR). Without this bridge `guia.perguntas` is undefined →
 * the panel renders "Nenhum guia gerado ainda." for EVERY persisted guide, however created.
 *
 * Bridged in the SERVICE READ LAYER ONLY (exact precedent: `normalizeCompetencia` for the
 * transcript analysis, CR-04) — the EF write is NOT renamed (it keeps `questions`/
 * `competency`, which `weakDimsFromScores` + the coverage check read). Non-lossy: the
 * original EF keys are preserved via spread. An incompleto guia (no `questions`) and a
 * guia already in pt-BR (`perguntas` present) pass through untouched.
 *
 * CR-01/WR-01/WR-02 (key-shape collision): after an EF regen the `questions[]` array is
 * HETEROGENEOUS — fresh IA rows carry English keys (`question`/`competency`), but a
 * PRESERVED manual row carries the pt-BR keys (`pergunta`/`dimensao`) because the RPC
 * wrote it that way and the EF merge concatenated it verbatim. Deriving `pergunta`
 * SOLELY from `q.question` blanked the manual row's text (it has none) — data loss to
 * the RH. The fix reads BOTH shapes per element: `pergunta = q.pergunta ?? q.question`
 * and `dimensao = q.dimensao ?? q.competency`, so a manual row in either shape renders
 * its real text/dimension regardless of which writer last touched it.
 */
export function normalizeGuia(guia: EntrevistaGuiaRow['guia']): EntrevistaGuiaRow['guia'] {
  if (!guia || typeof guia !== 'object') return guia
  // Already pt-BR (defensive — e.g. a future EF emitting `perguntas`): leave as-is.
  if (Array.isArray((guia as { perguntas?: unknown }).perguntas)) return guia
  const questions = (guia as { questions?: EfGuiaQuestion[] }).questions
  if (!Array.isArray(questions)) return guia
  const perguntas: GuiaPergunta[] = questions.map((q) => ({
    ...q,
    // CR-01: a preserved manual row carries `pergunta` (no `question`); fall back to it
    // so its text survives a regen-merge instead of normalizing to '' (silent data loss).
    pergunta:
      typeof q.pergunta === 'string'
        ? q.pergunta
        : typeof q.question === 'string'
          ? q.question
          : '',
    // WR-02: likewise carry the manual row's `dimensao` when the English `competency`
    // is absent, so a preserved manual row keeps its dimension through the round-trip.
    dimensao:
      typeof q.dimensao === 'string'
        ? q.dimensao
        : typeof q.competency === 'string'
          ? q.competency
          : null,
    // ENTREV-08: the read layer is origem-aware. Provenance survives the read; a
    // missing/legacy/garbled value defaults to 'ia' (legacy guides are wholly
    // AI-generated — no data backfill, A2). Only an explicit 'manual' is preserved.
    origem: q.origem === 'manual' ? 'manual' : 'ia',
  }))
  return { ...guia, perguntas }
}

/**
 * Reads the latest interview guide for a candidatura (RH/admin only — candidate
 * denied by RLS). Allowlist projection of `entrevista_guias`. Returns null when
 * no guide has been generated yet. Normalizes the EF OUTPUT shape (questions[]/
 * competency) → the pt-BR perguntas[] the panel reads (ENTREV-GUIA-DISPLAY-01).
 */
export async function getGuia(candidaturaId: string): Promise<EntrevistaGuiaRow | null> {
  if (!candidaturaId) {
    throw new EntrevistaServiceError('candidaturaId é obrigatório', 'INVALID_INPUT')
  }
  const { data, error } = await supabase
    .from('entrevista_guias')
    .select(ENTREVISTA_ALLOWLIST)
    .eq('candidatura_id', candidaturaId)
    .order('created_at', { ascending: false })
    .limit(1)

  if (error) {
    throw new EntrevistaServiceError(
      `Não foi possível carregar o guia: ${error.message}`,
      'DATABASE_ERROR',
      error,
    )
  }
  const rows = (data as unknown as EntrevistaGuiaRow[] | null) ?? []
  const row = rows[0] ?? null
  if (!row) return null
  // Bridge the EF OUTPUT shape (questions[]/competency) → the pt-BR perguntas[] the
  // panel reads (ENTREV-GUIA-DISPLAY-01). Without this every guide rendered empty.
  return { ...row, guia: normalizeGuia(row.guia) }
}

/**
 * Normalizes one persisted competency entry (CR-04). The EF writes the English key
 * `competency` (`extractCompetencias` in avaliar-transcricao-entrevista/index.ts);
 * every RH consumer reads the pt-BR key `competencia`. We bridge the two in the
 * SERVICE READ LAYER ONLY — the EF write is NOT renamed (gerar-guia's
 * weakDimsFromScores keeps reading `competency`, IN-03). A missing label falls
 * through to an empty string so the UI filters/keys never crash.
 */
function normalizeCompetencia(c: AnaliseCompetencia): AnaliseCompetencia {
  return {
    ...c,
    competencia:
      typeof c.competencia === 'string' && c.competencia.length > 0
        ? c.competencia
        : typeof c.competency === 'string'
          ? c.competency
          : '',
    score: typeof c.score === 'number' ? c.score : null,
  }
}

/**
 * Reads the latest transcript analysis for a candidatura. Allowlist projection of
 * `entrevista_analises` (transcript competencies + citations + the flag + the
 * human-review markers). Returns null when no transcript has been analyzed yet.
 *
 * CR-04: the EF persists the English `competency` key; this read normalizes it to
 * the pt-BR `competencia` the RH UI (scorecard + transcript panel) reads, so the
 * AI-seeded competencies actually reach the workspace (ENTREV-03).
 */
export async function getAnalise(
  candidaturaId: string,
): Promise<EntrevistaAnaliseRow | null> {
  if (!candidaturaId) {
    throw new EntrevistaServiceError('candidaturaId é obrigatório', 'INVALID_INPUT')
  }
  const { data, error } = await supabase
    .from('entrevista_analises')
    .select(ENTREVISTA_ANALISE_ALLOWLIST)
    .eq('candidatura_id', candidaturaId)
    .order('created_at', { ascending: false })
    .limit(1)

  if (error) {
    throw new EntrevistaServiceError(
      `Não foi possível carregar a análise da transcrição: ${error.message}`,
      'DATABASE_ERROR',
      error,
    )
  }
  const rows = (data as unknown as EntrevistaAnaliseRow[] | null) ?? []
  const row = rows[0] ?? null
  if (!row) return null
  // CR-04: normalize the EF's English `competency` → the pt-BR `competencia` the
  // RH components read. competencias/citacoes/bias_flags all carry the English key.
  return {
    ...row,
    competencias: Array.isArray(row.competencias)
      ? row.competencias.map(normalizeCompetencia)
      : row.competencias,
  }
}

/**
 * Reads the interview + cognitive score rows for a candidatura (the inline
 * scorecard reads `tipo='entrevista'`; the cognitive band reads `tipo='cognitivo'`).
 * Allowlist projection of `scores_candidato` — never a star projection.
 */
export async function getScores(candidaturaId: string): Promise<EntrevistaScoreRow[]> {
  if (!candidaturaId) {
    throw new EntrevistaServiceError('candidaturaId é obrigatório', 'INVALID_INPUT')
  }
  const { data, error } = await supabase
    .from('scores_candidato')
    .select(ENTREVISTA_SCORES_ALLOWLIST)
    .eq('candidatura_id', candidaturaId)
    .in('tipo', ['entrevista', 'cognitivo'])
    .limit(READ_LIMIT)

  if (error) {
    throw new EntrevistaServiceError(
      `Não foi possível carregar as avaliações: ${error.message}`,
      'DATABASE_ERROR',
      error,
    )
  }
  return (data as unknown as EntrevistaScoreRow[] | null) ?? []
}

// ── Writes — RPC + EF invokes ────────────────────────────────────────────────

/** Maps a Postgres/PostgREST error code to the service error union. */
function mapRpcError(error: unknown, fallbackMsg: string): EntrevistaServiceError {
  const code = (error as { code?: string }).code ?? ''
  if (code === '42501') {
    return new EntrevistaServiceError(
      'Você não tem permissão para esta avaliação.',
      'FORBIDDEN',
      error,
    )
  }
  if (code === '23514') {
    return new EntrevistaServiceError(
      'Dados inválidos. Verifique os campos.',
      'INVALID_INPUT',
      error,
    )
  }
  if (code === 'P0002' || code === 'no_data_found') {
    return new EntrevistaServiceError('Registro não encontrado.', 'NOT_FOUND', error)
  }
  return new EntrevistaServiceError(fallbackMsg, 'NETWORK_ERROR', error)
}

/** Payload for the inline scorecard save (BARS notas_humanas + optional notes). */
export interface SalvarAvaliacaoPayload {
  scoresHumanos: Record<string, number>
  notas: string
}

/**
 * Records the gestor's interview scorecard via the LIVE `salvar_avaliacao_entrevista`
 * SECURITY DEFINER RPC — NEVER a direct UPDATE. The RPC enforces role + own-vaga and
 * NEVER advances the funil / auto-rejects (RNF-07a). Error map: 42501 → FORBIDDEN,
 * 23514 → INVALID_INPUT, P0002/no_data_found → NOT_FOUND, else → NETWORK_ERROR.
 */
export async function salvarAvaliacao(
  candidaturaId: string,
  payload: SalvarAvaliacaoPayload,
): Promise<void> {
  if (!candidaturaId) {
    throw new EntrevistaServiceError('candidaturaId é obrigatório', 'INVALID_INPUT')
  }
  const { error } = await supabase.rpc('salvar_avaliacao_entrevista', {
    p_candidatura_id: candidaturaId,
    p_scores_humanos: payload.scoresHumanos,
    p_notas: payload.notas ?? '',
  })
  if (error) {
    throw mapRpcError(error, 'Não foi possível salvar a avaliação. Tente novamente.')
  }
}

/**
 * Persists the RH-edited interview guide via the LIVE `save_entrevista_guia_edits`
 * SECURITY DEFINER RPC (20-02) — NEVER a direct UPDATE. The RPC enforces role
 * (derived from `usuarios_rh`, not the JWT claim — ENTREV-08) + own-vaga and stores
 * the `perguntas[]` array as OPAQUE jsonb. It NEVER writes `candidaturas`, NEVER
 * advances the funil / auto-rejects (RNF-07a). The client stamps `origem:'manual'`
 * on RH-added rows (20-04 edit state); this service passes the array verbatim.
 *
 * Anti-tamper (T-20-09): the payload carries only the edited `perguntas[]` —
 * pergunta/dimensao/origem — never a top-level score/band/veredito; the guide is a
 * recommendation that never feeds candidaturas. Error map (reuses mapRpcError
 * verbatim): 42501 → FORBIDDEN, 23514 → INVALID_INPUT, P0002/no_data_found →
 * NOT_FOUND, else → NETWORK_ERROR — the raw RPC error/PII is NEVER surfaced. Reads
 * the guide back via the allowlist (origem default 'ia') so callers get the fresh row.
 */
export async function saveGuiaEdits(
  candidaturaId: string,
  tipo: TipoEntrevista,
  perguntas: GuiaPergunta[],
): Promise<EntrevistaGuiaRow | null> {
  if (!candidaturaId) {
    throw new EntrevistaServiceError('candidaturaId é obrigatório', 'INVALID_INPUT')
  }
  const { error } = await supabase.rpc('save_entrevista_guia_edits', {
    p_candidatura_id: candidaturaId,
    p_tipo: tipo,
    // The RPC stores opaque jsonb (database.types.ts types p_guia as `Json`); the
    // GuiaPergunta index signature (`[k:string]:unknown`) is structurally wider than
    // Json, so cast at the RPC boundary (precedent: configVagaService p_opcoes).
    p_guia: { perguntas } as unknown as Json,
  })
  if (error) {
    throw mapRpcError(error, 'Não foi possível salvar as edições do guia. Tente novamente.')
  }
  // The RPC upserts entrevista_guias; read it back via the allowlist (origem default 'ia').
  return getGuia(candidaturaId)
}

/** The EF body for guide generation — identifiers + tipo ONLY (anti-tamper). */
interface GerarGuiaBody {
  candidatura_id: string
  vaga_id: string
  tipo: TipoEntrevista
}

/**
 * Invokes the LIVE `gerar-guia-entrevista` EF. The client body carries ONLY
 * `{ candidatura_id, vaga_id, tipo }` — never a score/band (the 14-01 contract
 * test parses this exact shape under the EF `.strict()` schema). Returns the
 * freshly-generated guide row.
 */
export async function gerarGuia(
  candidaturaId: string,
  vagaId: string,
  tipo: TipoEntrevista,
): Promise<EntrevistaGuiaRow | null> {
  if (!candidaturaId || !vagaId) {
    throw new EntrevistaServiceError('candidaturaId e vagaId são obrigatórios', 'INVALID_INPUT')
  }
  const body: GerarGuiaBody = { candidatura_id: candidaturaId, vaga_id: vagaId, tipo }
  const { error } = await supabase.functions.invoke('gerar-guia-entrevista', { body })
  if (error) {
    throw new EntrevistaServiceError(
      'Não foi possível gerar o guia. Tente novamente.',
      'NETWORK_ERROR',
      error,
    )
  }
  // The EF persists to entrevista_guias; read it back via the allowlist.
  return getGuia(candidaturaId)
}

/** The EF body for transcript analysis — identifier + raw text ONLY (anti-tamper). */
interface AvaliarTranscricaoBody {
  candidatura_id: string
  transcricao: string
}

/**
 * Server-authoritative minimum transcript length (mirrors the EF
 * `MIN_TRANSCRICAO_LEN = 200` in avaliar-transcricao-entrevista/index.ts). WR-05:
 * the client guards this BEFORE invoking so a too-short transcript surfaces a
 * specific, non-retryable message instead of a generic network error.
 */
export const MIN_TRANSCRICAO_LEN = 200

/**
 * Invokes the LIVE `avaliar-transcricao-entrevista` EF. The client body carries
 * ONLY `{ candidatura_id, transcricao }` — the transcript is UNTRUSTED text and
 * the EF does injection-detect + maskPII server-side. Never a score/band on the
 * body (the 14-01 contract test parses this exact shape). Returns the freshly
 * persisted analysis row.
 */
export async function analisarTranscricao(
  candidaturaId: string,
  transcricao: string,
): Promise<EntrevistaAnaliseRow | null> {
  if (!candidaturaId) {
    throw new EntrevistaServiceError('candidaturaId é obrigatório', 'INVALID_INPUT')
  }
  if (!transcricao || transcricao.trim().length === 0) {
    throw new EntrevistaServiceError('A transcrição é obrigatória.', 'INVALID_INPUT')
  }
  // WR-05: mirror the EF's 200-char floor client-side with a SPECIFIC pt-BR message
  // — a too-short transcript is a deterministic validation failure, not a retryable
  // network error.
  if (transcricao.trim().length < MIN_TRANSCRICAO_LEN) {
    throw new EntrevistaServiceError(
      `A transcrição é muito curta para análise (mínimo de ${MIN_TRANSCRICAO_LEN} caracteres).`,
      'INVALID_INPUT',
    )
  }
  const body: AvaliarTranscricaoBody = {
    candidatura_id: candidaturaId,
    transcricao,
  }
  const { data, error } = await supabase.functions.invoke('avaliar-transcricao-entrevista', {
    body,
  })
  if (error) {
    // WR-05: surface the EF `error_code:'VALIDATION'` distinctly instead of
    // collapsing every EF error into NETWORK_ERROR. The FunctionsHttpError carries
    // the parsed body on `context` (a Response); fall back to the error shape.
    const efCode = await extractEfErrorCode(data, error)
    if (efCode === 'VALIDATION') {
      throw new EntrevistaServiceError(
        'A transcrição não passou na validação. Verifique se há texto suficiente para análise.',
        'INVALID_INPUT',
        error,
      )
    }
    throw new EntrevistaServiceError(
      'Não foi possível analisar a transcrição. Tente novamente.',
      'NETWORK_ERROR',
      error,
    )
  }
  // The EF persists to entrevista_analises; read it back via the allowlist.
  return getAnalise(candidaturaId)
}

/**
 * Confirms human review on the transcript analysis — sets
 * `entrevista_analises.revisao_confirmada_em`, which the server `avancar_etapa`
 * guard reads to RELEASE the language/accent flag block (RF-24 / RNF-07a). This
 * is the only enabled path out of the flag block; the human always decides.
 *
 * CR-03 + WR-07: routes through the `confirmar_revisao_entrevista` SECURITY DEFINER
 * RPC (role + vaga-ownership guarded) — NEVER a direct UPDATE. `entrevista_analises`
 * has RLS with only a SELECT policy, so a client UPDATE would be RLS-filtered to a
 * silent 0-row no-op (no error, no write). The RPC RETURNS the updated row; we ASSERT
 * the marker landed and throw NOT_FOUND when nothing came back — no silent success.
 * Error map: 42501 → FORBIDDEN, P0002/no_data_found → NOT_FOUND, else → NETWORK_ERROR.
 */
export async function confirmarRevisaoHumana(analiseId: string): Promise<void> {
  if (!analiseId) {
    throw new EntrevistaServiceError('analiseId é obrigatório', 'INVALID_INPUT')
  }
  // `confirmar_revisao_entrevista` (14-07 migration) is live in PROD + present in the
  // regenerated database.types.ts union — no cast needed.
  const { data, error } = await supabase.rpc('confirmar_revisao_entrevista', {
    p_analise_id: analiseId,
  })

  if (error) {
    throw mapRpcError(error, 'Não foi possível confirmar a revisão. Tente novamente.')
  }

  // Readback assertion (WR-07): the RPC returns the updated row carrying
  // revisao_confirmada_em. A null/empty return means nothing was confirmed —
  // surface NOT_FOUND instead of an optimistic "released".
  const row = Array.isArray(data) ? data[0] : data
  const marker = (row as { revisao_confirmada_em?: string | null } | null)?.revisao_confirmada_em
  if (!row || !marker) {
    throw new EntrevistaServiceError(
      'A análise não foi encontrada ou a revisão não pôde ser confirmada.',
      'NOT_FOUND',
      data,
    )
  }
}

/**
 * Records an AUDIT-ONLY cognitive-band ressalva in `bias_audit_log` (ENTREV-05 /
 * RNF-07a / RF-27). WR-03: this does NOT reject the candidate — the cognitive band
 * never decides; the real auditable rejection is the Phase-15 decisão final. The UI
 * forces an expanded justification and writes this audit row. NEVER advances/decides
 * the funil here — this is the audit trail, the human owns the decision elsewhere.
 */
export async function registrarRejeicaoCognitiva(input: {
  candidaturaId: string
  banda: BandaCognitiva | string | null
  justificativa: string
  flagDemografico?: boolean
}): Promise<void> {
  if (!input.candidaturaId) {
    throw new EntrevistaServiceError('candidaturaId é obrigatório', 'INVALID_INPUT')
  }
  if (!input.justificativa || input.justificativa.trim().length === 0) {
    throw new EntrevistaServiceError(
      'A justificativa expandida é obrigatória ao rejeitar com base no raciocínio lógico.',
      'INVALID_INPUT',
    )
  }
  const { error } = await supabase.from('bias_audit_log').insert({
    dados: {
      tipo: 'rejeicao_cognitiva',
      candidatura: input.candidaturaId,
      banda: input.banda ?? null,
      motivo: input.justificativa,
      flag_demografico: input.flagDemografico ?? false,
    },
  })
  if (error) {
    throw mapRpcError(error, 'Não foi possível registrar a auditoria. Tente novamente.')
  }
}
