-- =============================================================================
-- Migration: Baseline schema (Phase 1 Plan 04, per D-02)
-- Date: 2026-04-19
-- Requirement: FOUND-09
-- =============================================================================
--
-- PURPOSE
-- This baseline captures the current production schema at the start of
-- Phase 1 so that `supabase/migrations/` becomes the authoritative source
-- of truth going forward. Subsequent forward migrations (numbered
-- 20260420000001+) modify this baseline.
--
-- GENERATION METHOD
-- Ideally this file is produced by `npx supabase db dump --schema public`
-- against the production database and committed verbatim. At the time
-- this file was authored, direct DB dump access was unavailable from the
-- execution environment (worktree agent, no Supabase project link), so the
-- baseline was reconstructed from two authoritative sources:
--   1. `database.types.ts` (generated by Supabase CLI from prod, checked in)
--   2. Legacy migration files archived to `docs/sql/legacy/`
--
-- The reconstruction covers the 4 core domain tables (candidatos, vagas,
-- candidaturas, usuarios_rh) plus `logs_acesso` (from legacy migration
-- 20250116) and the 3 enum types visible in database.types.ts.
--
-- !!! TODO: VALIDATE AGAINST PROD BEFORE APPLY !!!
-- Before running `supabase db reset` with this baseline on any environment
-- other than a throwaway branch, regenerate this file via:
--   npx supabase link --project-ref isljnozzlvckrgjjbjwp
--   npx supabase db dump --linked --schema public --file supabase/migrations/20260419000000_baseline.sql
-- Then run `npm run db:types` + `npm run lint` to confirm types still compile.
-- The RLS policies and grants in THIS reconstruction are a best-effort guess
-- informed by CLAUDE.md security conventions (RLS on 100% of user-data tables).
-- Real policy wording must be dumped from prod.
--
-- DATA POLICY
-- Schema-only. No user data. Dev seed lives in `supabase/seed.sql`.
-- =============================================================================

BEGIN;

-- -------------------------------------------------------------------------
-- Extensions required
-- -------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- gen_random_uuid()

-- -------------------------------------------------------------------------
-- Enum types (mirrors database.types.ts `public.Enums`)
-- -------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_vaga') THEN
    CREATE TYPE public.status_vaga AS ENUM ('rascunho', 'ativa', 'inativa', 'arquivada');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_candidatura') THEN
    CREATE TYPE public.status_candidatura AS ENUM (
      'aguardando_resposta',
      'em_analise',
      'aprovado_proxima',
      'rejeitado',
      'finalizado'
    );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'etapa_processo') THEN
    CREATE TYPE public.etapa_processo AS ENUM (
      'triagem',
      'bigfive',
      'disc',
      'entrevista_online',
      'raven',
      'cultura',
      'entrevista_presencial',
      'avaliacao_final',
      'aprovado',
      'rejeitado'
    );
  END IF;
END $$;

COMMENT ON TYPE public.etapa_processo IS 'Etapas do processo seletivo: triagem -> bigfive -> disc -> entrevista_online -> raven (cognitivo) -> entrevista_presencial -> cultura -> avaliacao_final -> aprovado/rejeitado';

-- =========================================================================
-- Table: candidatos
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.candidatos (
  id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome_completo          TEXT NOT NULL,
  email                  TEXT NOT NULL,
  celular                TEXT NOT NULL,
  cpf                    TEXT NOT NULL,
  data_nascimento        DATE NOT NULL,
  cidade                 TEXT NOT NULL,
  estado                 TEXT NOT NULL,
  logradouro             TEXT,
  numero                 TEXT,
  bairro                 TEXT,
  cep                    TEXT,
  complemento            TEXT,
  genero                 TEXT,
  linkedin               TEXT,
  linkedin_url           TEXT,
  instagram              TEXT,
  instagram_url          TEXT,
  avatar_url             TEXT,
  ativo                  BOOLEAN NOT NULL DEFAULT true,
  bloqueado              BOOLEAN NOT NULL DEFAULT false,
  bloqueado_motivo       TEXT,
  email_verificado       BOOLEAN NOT NULL DEFAULT false,
  data_ultimo_acesso     TIMESTAMPTZ,
  como_conheceu          TEXT,
  como_conheceu_detalhes TEXT,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by             UUID,
  updated_by             UUID,
  deleted_at             TIMESTAMPTZ,
  -- Unique constraints for duplicate detection
  CONSTRAINT candidatos_cpf_key   UNIQUE (cpf),
  CONSTRAINT candidatos_email_key UNIQUE (email),
  CONSTRAINT candidatos_user_id_key UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_candidatos_user_id ON public.candidatos(user_id);
CREATE INDEX IF NOT EXISTS idx_candidatos_cpf     ON public.candidatos(cpf);
CREATE INDEX IF NOT EXISTS idx_candidatos_email   ON public.candidatos(email);
CREATE INDEX IF NOT EXISTS idx_candidatos_deleted_at ON public.candidatos(deleted_at) WHERE deleted_at IS NULL;

ALTER TABLE public.candidatos ENABLE ROW LEVEL SECURITY;

-- NOTE: Baseline RLS policies are captured here best-effort. Forward migration
-- 20260420000001_rls_anon_to_rpc.sql removes any anon SELECT that may exist.
-- The canonical policy list must be reconciled from prod via supabase db dump.
DROP POLICY IF EXISTS "candidatos_select_own"  ON public.candidatos;
DROP POLICY IF EXISTS "candidatos_update_own"  ON public.candidatos;
DROP POLICY IF EXISTS "candidatos_insert_self" ON public.candidatos;

CREATE POLICY "candidatos_select_own"
  ON public.candidatos FOR SELECT
  TO authenticated
  USING (user_id = (SELECT auth.uid()));

CREATE POLICY "candidatos_update_own"
  ON public.candidatos FOR UPDATE
  TO authenticated
  USING (user_id = (SELECT auth.uid()))
  WITH CHECK (user_id = (SELECT auth.uid()));

-- Insert is performed by the cadastrar-candidato Edge Function with service_role.
-- No anon/authenticated insert policy — intentionally blocked at RLS level.

-- =========================================================================
-- Table: vagas
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.vagas (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  titulo                   TEXT NOT NULL,
  slug                     TEXT NOT NULL,
  subtitulo                TEXT,
  descricao_curta          TEXT,
  sobre_cargo              TEXT,
  sobre_empresa            TEXT,
  responsabilidades        TEXT,
  requisitos_formacao      TEXT,
  requisitos_experiencia   TEXT,
  requisitos_tecnicos      TEXT,
  requisitos_habilidades   TEXT,
  beneficios               TEXT,
  diferenciais             TEXT,
  perfil_ideal             TEXT,
  departamento             TEXT,
  cidade                   TEXT,
  estado                   TEXT,
  endereco_completo        TEXT,
  modelo_trabalho          TEXT,
  tipo_contrato            TEXT,
  jornada_trabalho         TEXT,
  nivel_senioridade        TEXT,
  faixa_salarial_min       NUMERIC,
  faixa_salarial_max       NUMERIC,
  exibir_salario           BOOLEAN DEFAULT false,
  total_vagas              INTEGER,
  data_abertura            DATE,
  data_fechamento          DATE,
  status                   public.status_vaga NOT NULL DEFAULT 'rascunho',
  prompt_ia_descricao      TEXT,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by               UUID,
  updated_by               UUID,
  deleted_at               TIMESTAMPTZ,
  CONSTRAINT vagas_slug_key UNIQUE (slug)
);

CREATE INDEX IF NOT EXISTS idx_vagas_status ON public.vagas(status);
CREATE INDEX IF NOT EXISTS idx_vagas_slug   ON public.vagas(slug);
CREATE INDEX IF NOT EXISTS idx_vagas_deleted_at ON public.vagas(deleted_at) WHERE deleted_at IS NULL;

ALTER TABLE public.vagas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "vagas_select_active_public" ON public.vagas;
DROP POLICY IF EXISTS "vagas_rh_full_access"       ON public.vagas;

-- Public listing of ACTIVE vagas (candidates and anon users can browse jobs)
CREATE POLICY "vagas_select_active_public"
  ON public.vagas FOR SELECT
  TO anon, authenticated
  USING (status = 'ativa' AND deleted_at IS NULL);

-- RH users get full access (inspected via usuarios_rh + role check)
CREATE POLICY "vagas_rh_full_access"
  ON public.vagas FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.usuarios_rh u
      WHERE u.user_id = (SELECT auth.uid())
        AND u.ativo = true
        AND u.deleted_at IS NULL
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.usuarios_rh u
      WHERE u.user_id = (SELECT auth.uid())
        AND u.ativo = true
        AND u.deleted_at IS NULL
    )
  );

-- =========================================================================
-- Table: usuarios_rh
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.usuarios_rh (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome_completo      TEXT NOT NULL,
  email              TEXT NOT NULL,
  cargo              TEXT NOT NULL,
  role               TEXT NOT NULL,  -- 'recrutador' | 'administrador'
  telefone           TEXT,
  avatar_url         TEXT,
  ativo              BOOLEAN NOT NULL DEFAULT true,
  primeiro_acesso    BOOLEAN NOT NULL DEFAULT true,
  data_ultimo_login  TIMESTAMPTZ,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by         UUID,
  updated_by         UUID,
  deleted_at         TIMESTAMPTZ,
  CONSTRAINT usuarios_rh_user_id_key UNIQUE (user_id),
  CONSTRAINT usuarios_rh_email_key   UNIQUE (email),
  CONSTRAINT usuarios_rh_role_chk    CHECK (role IN ('recrutador', 'administrador'))
);

CREATE INDEX IF NOT EXISTS idx_usuarios_rh_user_id ON public.usuarios_rh(user_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_rh_ativo   ON public.usuarios_rh(ativo) WHERE deleted_at IS NULL;

ALTER TABLE public.usuarios_rh ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "usuarios_rh_select_self"       ON public.usuarios_rh;
DROP POLICY IF EXISTS "usuarios_rh_admin_full_access" ON public.usuarios_rh;

CREATE POLICY "usuarios_rh_select_self"
  ON public.usuarios_rh FOR SELECT
  TO authenticated
  USING (user_id = (SELECT auth.uid()));

CREATE POLICY "usuarios_rh_admin_full_access"
  ON public.usuarios_rh FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.usuarios_rh u
      WHERE u.user_id = (SELECT auth.uid())
        AND u.role = 'administrador'
        AND u.ativo = true
        AND u.deleted_at IS NULL
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.usuarios_rh u
      WHERE u.user_id = (SELECT auth.uid())
        AND u.role = 'administrador'
        AND u.ativo = true
        AND u.deleted_at IS NULL
    )
  );

-- =========================================================================
-- Table: candidaturas
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.candidaturas (
  id                                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  candidato_id                      UUID NOT NULL REFERENCES public.candidatos(id) ON DELETE CASCADE,
  vaga_id                           UUID NOT NULL REFERENCES public.vagas(id) ON DELETE CASCADE,
  status                            public.status_candidatura NOT NULL DEFAULT 'aguardando_resposta',
  etapa_atual                       public.etapa_processo NOT NULL DEFAULT 'triagem',
  feedback_rejeicao                 TEXT,
  score_geral                       NUMERIC,
  origem_candidatura                TEXT,
  is_rascunho                       BOOLEAN NOT NULL DEFAULT false,
  is_favorito                       BOOLEAN NOT NULL DEFAULT false,
  observacoes_rh                    TEXT,
  curriculo_url                     TEXT,
  curriculo_nome_original           TEXT,
  curriculo_tamanho_bytes           BIGINT,
  tempo_preenchimento_segundos      INTEGER,
  data_candidatura                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  data_formulario_enviado           TIMESTAMPTZ,
  data_bigfive_enviado              TIMESTAMPTZ,
  data_disc_enviado                 TIMESTAMPTZ,
  data_raven_enviado                TIMESTAMPTZ,
  data_entrevista_online            TIMESTAMPTZ,
  data_cultura_enviado              TIMESTAMPTZ,
  data_entrevista_presencial        TIMESTAMPTZ,
  data_decisao_final                TIMESTAMPTZ,
  analise_ia_formulario             JSONB,
  analise_ia_bigfive                JSONB,
  analise_ia_disc                   JSONB,
  analise_ia_raven                  JSONB,
  analise_ia_entrevista_online      JSONB,
  analise_ia_cultura                JSONB,
  analise_ia_entrevista_presencial  JSONB,
  created_at                        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by                        UUID,
  updated_by                        UUID,
  deleted_at                        TIMESTAMPTZ,
  CONSTRAINT candidaturas_candidato_vaga_key UNIQUE (candidato_id, vaga_id)
);

CREATE INDEX IF NOT EXISTS idx_candidaturas_candidato ON public.candidaturas(candidato_id);
CREATE INDEX IF NOT EXISTS idx_candidaturas_vaga      ON public.candidaturas(vaga_id);
CREATE INDEX IF NOT EXISTS idx_candidaturas_status    ON public.candidaturas(status);
CREATE INDEX IF NOT EXISTS idx_candidaturas_etapa     ON public.candidaturas(etapa_atual);

ALTER TABLE public.candidaturas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "candidaturas_candidato_own"   ON public.candidaturas;
DROP POLICY IF EXISTS "candidaturas_rh_full_access"  ON public.candidaturas;

-- Candidato sees only their own candidaturas
CREATE POLICY "candidaturas_candidato_own"
  ON public.candidaturas FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.candidatos c
      WHERE c.id = candidato_id AND c.user_id = (SELECT auth.uid())
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.candidatos c
      WHERE c.id = candidato_id AND c.user_id = (SELECT auth.uid())
    )
  );

CREATE POLICY "candidaturas_rh_full_access"
  ON public.candidaturas FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.usuarios_rh u
      WHERE u.user_id = (SELECT auth.uid()) AND u.ativo = true AND u.deleted_at IS NULL
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.usuarios_rh u
      WHERE u.user_id = (SELECT auth.uid()) AND u.ativo = true AND u.deleted_at IS NULL
    )
  );

-- =========================================================================
-- Table: logs_acesso  (carried forward from legacy 20250116 migration)
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.logs_acesso (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  evento            VARCHAR(50) NOT NULL,
  user_id           UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  email_tentativa   VARCHAR(255),
  ip_address        VARCHAR(45),
  country           VARCHAR(100),
  city              VARCHAR(100),
  device_info       TEXT,
  device_type       VARCHAR(20),
  browser           VARCHAR(100),
  operating_system  VARCHAR(100),
  erro_mensagem     TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.logs_acesso IS 'Registro de eventos de acesso e seguranca do sistema';

CREATE INDEX IF NOT EXISTS idx_logs_acesso_evento           ON public.logs_acesso(evento);
CREATE INDEX IF NOT EXISTS idx_logs_acesso_user_id          ON public.logs_acesso(user_id);
CREATE INDEX IF NOT EXISTS idx_logs_acesso_created_at       ON public.logs_acesso(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_logs_acesso_ip_address       ON public.logs_acesso(ip_address);
CREATE INDEX IF NOT EXISTS idx_logs_acesso_email_tentativa  ON public.logs_acesso(email_tentativa);
CREATE INDEX IF NOT EXISTS idx_logs_acesso_security_analysis
  ON public.logs_acesso(evento, ip_address, created_at DESC);

ALTER TABLE public.logs_acesso ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Servico pode inserir logs"          ON public.logs_acesso;
DROP POLICY IF EXISTS "Service role pode ler todos os logs" ON public.logs_acesso;
DROP POLICY IF EXISTS "Service role pode deletar logs"     ON public.logs_acesso;

CREATE POLICY "Servico pode inserir logs"
  ON public.logs_acesso FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Service role pode ler todos os logs"
  ON public.logs_acesso FOR SELECT TO service_role USING (true);

CREATE POLICY "Service role pode deletar logs"
  ON public.logs_acesso FOR DELETE TO service_role USING (true);

GRANT INSERT ON public.logs_acesso TO anon;
GRANT INSERT ON public.logs_acesso TO authenticated;
GRANT ALL    ON public.logs_acesso TO service_role;

-- =========================================================================
-- Updated_at triggers
-- =========================================================================
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DO $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT c.relname AS table_name
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_attribute a ON a.attrelid = c.oid
    WHERE n.nspname = 'public'
      AND c.relkind = 'r'
      AND a.attname = 'updated_at'
      AND c.relname IN ('candidatos', 'vagas', 'candidaturas', 'usuarios_rh')
  LOOP
    EXECUTE format(
      'DROP TRIGGER IF EXISTS trg_%I_touch_updated_at ON public.%I;
       CREATE TRIGGER trg_%I_touch_updated_at
         BEFORE UPDATE ON public.%I
         FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();',
      r.table_name, r.table_name, r.table_name, r.table_name
    );
  END LOOP;
END $$;

COMMIT;

-- =============================================================================
-- END OF BASELINE
-- See README at docs/sql/legacy/README.md for migration history.
-- =============================================================================
