-- =============================================================================
-- Migration: devolutivas_candidato — Big Five D-lite devolutiva sink + RLS
-- Date: 2026-06-12
-- Phase: 12 (big-five-devolutiva — Etapa 3 contextual assessment)
-- Requirement: AVAL-08 (RF-19a / RF-19b) — Big Five devolutiva (in-app + email)
-- =============================================================================
--
-- PURPOSE
-- Persists the candidate-facing Big Five devolutiva (5 dims + percentil + band +
-- ~150-200 words/dim + LGPD disclaimers) generated by gerar-devolutiva-bigfive
-- (hybrid: 25 official band templates + IA polish). conteudo_jsonb holds the
-- BigfiveDevolutivaSchema structured output. ONLY Big Five — never SJT/Redação
-- (RF-19b guard lives in the EF). Audit fields per PRD RFB-15 (modelo_ia,
-- prompt_version) — LGPD-02 traceability (100% of IA suggestions auditable).
--
-- SECURITY / RLS (T-12-07):
-- UNLIKE scores_candidato (which the candidato CANNOT read), the devolutiva is FOR
-- the candidate → candidate own-row SELECT is correct here. RH/admin also read
-- (allowlist). Writes happen ONLY via service_role (the EF) — there is NO candidate
-- INSERT/UPDATE policy. Reads still use explicit allowlists in the app layer, never
-- select('*') ([[reference_select_star_leaks_pii]]).
--
-- NOTE: No explicit `BEGIN; ... COMMIT;` wrapper (D-22 — CLAUDE.md §Commands). This
-- file is table-only DDL + policies (no $$ body) → pushes clean like scores_candidato.
-- NOT applied here — application is the [BLOCKING] 12-06 apply wave (CONTEXT).
-- =============================================================================

-- Big Five devolutiva sink (NEW table) ------------------------------------------
CREATE TABLE public.devolutivas_candidato (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  candidatura_id  uuid NOT NULL REFERENCES public.candidaturas(id) ON DELETE CASCADE,
  candidato_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  conteudo_jsonb  jsonb NOT NULL,                          -- BigfiveDevolutivaSchema structured output
  modelo_ia       text,                                    -- audit (PRD RFB-15): which model polished the text
  prompt_version  text,                                    -- audit: bigfive_devolutiva prompt version (git→DB)
  created_at      timestamptz NOT NULL DEFAULT now(),
  -- One devolutiva per candidatura (idempotent regeneration upserts this row)
  UNIQUE (candidatura_id)
);

COMMENT ON TABLE public.devolutivas_candidato IS
  'Phase 12 / AVAL-08: Big Five D-lite devolutiva (5 dims + percentil + band + texto + LGPD disclaimers, conteudo_jsonb = BigfiveDevolutivaSchema). UNLIKE scores_candidato, this IS candidate-facing → candidate own-row SELECT. RH/admin read via allowlist. Writes ONLY via service_role EF (gerar-devolutiva-bigfive) — no candidate INSERT/UPDATE. ONLY Big Five (RF-19b). Reads never select(*) ([[reference_select_star_leaks_pii]]).';

CREATE INDEX idx_devolutivas_candidatura ON public.devolutivas_candidato (candidatura_id);
CREATE INDEX idx_devolutivas_candidato ON public.devolutivas_candidato (candidato_id);

ALTER TABLE public.devolutivas_candidato ENABLE ROW LEVEL SECURITY;

-- Candidate reads THEIR OWN devolutiva (own-row) --------------------------------
DROP POLICY IF EXISTS cand_le_sua_devolutiva ON public.devolutivas_candidato;
CREATE POLICY cand_le_sua_devolutiva ON public.devolutivas_candidato
  FOR SELECT
  USING (candidato_id = (select auth.uid()));

-- RH/admin read (allowlist — live idiom 'administrador', never 'admin') ----------
DROP POLICY IF EXISTS rh_le_devolutivas ON public.devolutivas_candidato;
CREATE POLICY rh_le_devolutivas ON public.devolutivas_candidato
  FOR SELECT
  USING ((select auth.jwt() #>> '{app_metadata,role}') IN ('rh', 'administrador'));

-- (no candidate/anon INSERT/UPDATE/DELETE policy → only service_role EF writes)
